version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: card_management_app_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - laravel_network
    command: >
      sh -c "composer install --no-dev --optimize-autoloader &&
             npm install && npm run build &&
             php artisan migrate:fresh --seed --force &&
             php-fpm"

  db:
    image: mysql:8.0
    container_name: card_management_app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: card_management_app
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --innodb_buffer_pool_size=512M
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: card_management_app_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
